### ISSUE TITLE
Display event notifications

### ISSUE THREAD

**Issue by cmichi** [paritytech/ink-workshop#21]
Follow-up to https://github.com/paritytech/ink-workshop/issues/20.

### ToDos
(1) For the events we should choose funny descriptions, inspired by the Worms games. There's likely even a page online that lists the notification texts for Worms. Can you check if you can find one? That would be ideal as inspiration.

(2) Please display those contract events in notifications that are ephemeral and fade-out after some time.

(3) Besides the contract emitted events you can think about adding notifications for events that the UI can derive on its own, e.g. "game about to end soon".

(4) For those funny descriptions, we should have an Array of ones to choose from and the UI should select one by random. So that it's not always the same text for "player registered", but instead things like "$player decided to join the party", "$player found his courage and joined", "$player in da house".

For other events we could have things like
* changes in the scoreboard: "Behold, $player just went to the top" or "$player decided to make an excursion to the end".

(5) Please already make this i18n ready, so that we can do the workshop in Spanish for Buenos Aires by just adding translations.

**Comment by DoubleOTheven** [comment]
This is almost done. @lean-apple helped get things set up. I'm adding Worms-like sayings now inspired by this:

https://www.youtube.com/watch?v=VhN2N3SfPYI 😎
