### ISSUE TITLE
Frontend doesn't start

### ISSUE THREAD

**Issue by 123oli** [paritytech/ink-workshop#54]
I have built and deploy ink-workshop smart contract in `contract ui` Shibuya testnet in [polkadotjs](https://polkadotjs-apps.web.app/#/contracts).  Then I started frontend and input `game contract address`. But game doesn't start instead it show this screen. Can anybody tell me why game doesn't start?

![Screenshot 2023-01-29 at 12 38 45](https://user-images.githubusercontent.com/42571338/215310676-3628ce0a-7a5d-43b4-9839-e7f727ec8632.JPG)

**Comment by athei** [comment]
Because unless you changed that the UI is configured to look for that contract on Rococo.
